//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerStatu
    {
        public AnswerStatu()
        {
            this.CustomerAnswers = new HashSet<CustomerAnswer>();
        }
    
        public int statusValue { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<CustomerAnswer> CustomerAnswers { get; set; }
    }
}
