//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AnswerOption
    {
        public AnswerOption()
        {
            this.CustomerAnswers = new HashSet<CustomerAnswer>();
        }
    
        public int questionId { get; set; }
        public int answerNumber { get; set; }

        [Required(ErrorMessage = "Answer option text is mandatory!")]
        [DisplayName("Answer option text")]
        [StringLength(1000, ErrorMessage = "Answer option text cannot exceed 1000 characters.")]
        [DataType(DataType.MultilineText)]
        public string answerText { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<CustomerAnswer> CustomerAnswers { get; set; }
    }
}
