//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOption
    {
        public int questionId { get; set; }
        public int answerNumber { get; set; }
        public string answerText { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
