//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerSurveys = new HashSet<CustomerSurvey>();
        }
    
        public int customerId { get; set; }
        public string companyName { get; set; }
        public string contactFirstName { get; set; }
        public string contactLastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<CustomerSurvey> CustomerSurveys { get; set; }
    }
}
