//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAnswer
    {
        public int surveyId { get; set; }
        public int customerId { get; set; }
        public System.DateTime startDate { get; set; }
        public int questionId { get; set; }
        public int answerStatusValue { get; set; }
        public Nullable<int> answerOptionQuestionId { get; set; }
        public Nullable<int> answerOptionNumber { get; set; }
        public string answerText { get; set; }
        public int observerStatusValue { get; set; }
        public Nullable<int> countermeasureId1 { get; set; }
        public Nullable<int> countermeasureId2 { get; set; }
        public Nullable<int> countermeasureId3 { get; set; }
        public string observerComment { get; set; }
        public Nullable<System.DateTime> observerCommentDateAndTime { get; set; }
        public string supervisorComment { get; set; }
        public Nullable<System.DateTime> supervisorCommentDateAndTime { get; set; }
    
        public virtual AnswerOption AnswerOption { get; set; }
        public virtual AnswerStatu AnswerStatu { get; set; }
        public virtual CustomerSurvey CustomerSurvey { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure1 { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure2 { get; set; }
        public virtual ObserverStatu ObserverStatu { get; set; }
        public virtual Question Question { get; set; }
    }
}
