//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSurvey
    {
        public CustomerSurvey()
        {
            this.CustomerAnswers = new HashSet<CustomerAnswer>();
        }
    
        public int surveyId { get; set; }
        public int customerId { get; set; }
        public System.DateTime startDate { get; set; }
        public string startComment { get; set; }
        public string customerSurveyTitle { get; set; }
        public int observerUserId { get; set; }
        public int supervisorUserId { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string endComment { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerAnswer> CustomerAnswers { get; set; }
        public virtual GenericSurvey GenericSurvey { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
    }
}
