//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CustomerAnswer
    {
        public int surveyId { get; set; }
        public int questionId { get; set; }
        [DisplayName("Answer option")]
        public Nullable<int> answerOptionNumber { get; set; }

        [Required(ErrorMessage = "Answer text is mandatory!")]
        [DisplayName("Answer text")]
        [StringLength(500, ErrorMessage = "Answer text value cannot exceed 500 characters.")]
        [DataType(DataType.MultilineText)]
        public string answerText { get; set; }

        [DisplayName("Answer Status")]
        public Nullable<int> answerStatusValue { get; set; }

         [DisplayName("Observer Status")]
        public Nullable<int> observerStatusValue { get; set; }

        [DisplayName("Countermeasure 1")]
        public Nullable<int> countermeasureId1 { get; set; }

        [DisplayName("Countermeasure 2")]
        public Nullable<int> countermeasureId2 { get; set; }

        [DisplayName("Countermeasure 3")]
        public Nullable<int> countermeasureId3 { get; set; }

        [DisplayName("Observer comment")]
        [StringLength(1000, ErrorMessage = "Observer Comment value cannot exceed 1000 characters.")]
        [DataType(DataType.MultilineText)]
        public string observerComment { get; set; }

        [DisplayName("Observer comment Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        public Nullable<System.DateTime> observerCommentDateAndTime { get; set; }

        [DisplayName("Supervisor comment")]
        [StringLength(1000, ErrorMessage = "Supervisor Comment value cannot exceed 1000 characters.")]
        [DataType(DataType.MultilineText)]
        public string supervisorComment { get; set; }

        [DisplayName("Supervisor comment Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        public Nullable<System.DateTime> supervisorCommentDateAndTime { get; set; }
    
        public virtual AnswerOption AnswerOption { get; set; }
        public virtual AnswerStatu AnswerStatu { get; set; }
        public virtual CustomerSurvey CustomerSurvey { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure1 { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure2 { get; set; }
        public virtual ObserverStatu ObserverStatu { get; set; }
        public virtual Question Question { get; set; }
    }
}
