//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GenericCountermeasure
    {
        public GenericCountermeasure()
        {
            this.CustomerAnswers = new HashSet<CustomerAnswer>();
            this.CustomerAnswers1 = new HashSet<CustomerAnswer>();
            this.CustomerAnswers2 = new HashSet<CustomerAnswer>();
            this.GenericCountermeasure1 = new HashSet<GenericCountermeasure>();
        }
    
        public int countermeasureId { get; set; }
        public int questionId { get; set; }

        [Required(ErrorMessage = "Title is mandatory!")]
        [DisplayName("Title")]
        [StringLength(100, ErrorMessage = "Title value cannot exceed 100 characters.")]
        public string title { get; set; }

        [Required(ErrorMessage = "Description is mandatory!")]
        [DisplayName("Description")]
        [StringLength(1000, ErrorMessage = "Title value cannot exceed 1000 characters.")]
        [DataType(DataType.MultilineText)]
        public string description { get; set; }

        [Required(ErrorMessage = "Date is mandatory!")]
        [DisplayName("Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        public System.DateTime dateAndTime { get; set; }

        [DisplayName("Mother countermeasure")]
        public Nullable<int> motherCountermeasure { get; set; }
    
        public virtual ICollection<CustomerAnswer> CustomerAnswers { get; set; }
        public virtual ICollection<CustomerAnswer> CustomerAnswers1 { get; set; }
        public virtual ICollection<CustomerAnswer> CustomerAnswers2 { get; set; }
        public virtual ICollection<GenericCountermeasure> GenericCountermeasure1 { get; set; }
        public virtual GenericCountermeasure GenericCountermeasure2 { get; set; }
        public virtual Question Question { get; set; }
    }
}
