//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class QuestionType
    {
        public QuestionType()
        {
            this.Questions = new HashSet<Question>();
        }
        
        [DisplayName("Question Type Id")]
        public int questionTypeId { get; set; }

        [DisplayName("Question Type")]
        public string questionTypeName { get; set; }

        [DisplayName("Description")]
        public string description { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
