//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionType
    {
        public QuestionType()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int questionTypeId { get; set; }
        public string questionTypeName { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
