//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;  
    
    public partial class QuestionCategory
    {
        [Required(ErrorMessage = "Category Id is mandatory!")]
        [DisplayName("Category Id")]
        [StringLength(6)]
        public string categoryId { get; set; }

        [Required(ErrorMessage="Category name is mandatory!")]
        [DisplayName("Category Name")]
        [StringLength(40)]
        public string categoryName { get; set; }

        [Required(ErrorMessage = "Description is mandatory!")]
        [DisplayName("Description")]
        [StringLength(300)]
        public string description { get; set; }
    }
}
