//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.GenericSurveys = new HashSet<GenericSurvey>();
        }
    
        public string questionId { get; set; }
        public string categoryId { get; set; }
        public string questionTypeId { get; set; }
        public string questionTextMain { get; set; }
        public string questionTextExtra { get; set; }
        public string baseLevel2RequirementText { get; set; }
        public string additionalInfo { get; set; }
        public string additionalNote { get; set; }
    
        public virtual ICollection<GenericSurvey> GenericSurveys { get; set; }
    }
}
