//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public Question()
        {
            this.AnswerOptions = new HashSet<AnswerOption>();
            this.CustomerAnswers = new HashSet<CustomerAnswer>();
            this.GenericCountermeasures = new HashSet<GenericCountermeasure>();
            this.GenericSurveys = new HashSet<GenericSurvey>();
        }
    
        public int questionId { get; set; }
        public int categoryId { get; set; }
        public int questionTypeId { get; set; }

        [DataType(DataType.MultilineText)]
        public string questionTextMain { get; set; }

        [DataType(DataType.MultilineText)]
        public string questionTextExtra { get; set; }

        [DataType(DataType.MultilineText)]
        public string baseLevel2RequirementText { get; set; }

        [DataType(DataType.MultilineText)]
        public string additionalInfo { get; set; }

        [DataType(DataType.MultilineText)]
        public string additionalNote { get; set; }
    
        public virtual ICollection<AnswerOption> AnswerOptions { get; set; }
        public virtual ICollection<CustomerAnswer> CustomerAnswers { get; set; }
        public virtual ICollection<GenericCountermeasure> GenericCountermeasures { get; set; }
        public virtual QuestionCategory QuestionCategory { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<GenericSurvey> GenericSurveys { get; set; }
    }
}
