//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SecuritySurveyEntities : DbContext
    {
        public SecuritySurveyEntities()
            : base("name=SecuritySurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnswerOption> AnswerOptions { get; set; }
        public DbSet<GenericSurvey> GenericSurveys { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<QuestionCategory> QuestionCategories { get; set; }
        public DbSet<QuestionType> QuestionTypes { get; set; }
    
        public virtual int sp_01_CreateTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_01_CreateTables");
        }
    
        public virtual int sp_02_DropTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_02_DropTables");
        }
    
        public virtual int sp_03_DeleteData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_03_DeleteData");
        }
    
        public virtual int sp_04_InsertData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_04_InsertData");
        }
    
        public virtual int sp_05_RebuildDB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_05_RebuildDB");
        }
    }
}
