//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.CustomerSurveys = new HashSet<CustomerSurvey>();
            this.CustomerSurveys1 = new HashSet<CustomerSurvey>();
            this.GenericSurveys = new HashSet<GenericSurvey>();
        }
    
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public bool isTeacher { get; set; }
    
        public virtual ICollection<CustomerSurvey> CustomerSurveys { get; set; }
        public virtual ICollection<CustomerSurvey> CustomerSurveys1 { get; set; }
        public virtual ICollection<GenericSurvey> GenericSurveys { get; set; }
    }
}
