//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSecuritySurvey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.CustomerSurveys = new HashSet<CustomerSurvey>();
            this.CustomerSurveys1 = new HashSet<CustomerSurvey>();
            this.GenericSurveys = new HashSet<GenericSurvey>();
        }
    
        public int userId { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First name is required.")]
        [StringLength(100, ErrorMessage = "Maximum length of 100 characters.")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name is required.")]
        [StringLength(100, ErrorMessage = "Maximum length of 100 characters.")]
        public string lastName { get; set; }

        [Required(ErrorMessage = "Email is mandatory!")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email")]
        [StringLength(100, ErrorMessage = "Email cannot exceed 100 characters.")]
        public string email { get; set; }

        [DisplayName("Phone Number")]
        [StringLength(100, ErrorMessage = "Maximum length of 100 characters.")]
        public string phone { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is required.")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Minimum length is 4 characters. Maximum length of 50 characters.")]
        public string userName { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        [StringLength(50, MinimumLength = 6, ErrorMessage = "Minimum length is 6 characters. Maximum length of 50 characters.")]
        public string password { get; set; }

        [DisplayName("Teacher")]
        public bool isTeacher { get; set; }
    
        public virtual ICollection<CustomerSurvey> CustomerSurveys { get; set; }
        public virtual ICollection<CustomerSurvey> CustomerSurveys1 { get; set; }
        public virtual ICollection<GenericSurvey> GenericSurveys { get; set; }
    }
}
